export class DocumentoPagareServiceDTO {
    constructor(
      public readonly pagareId: number,
      public readonly amount: number,
      public readonly currency: string,
      public readonly dueDate: string, // se cambia de Date a string
      public readonly debtor: DebtorDTO,
      public readonly creditor: CreditorDTO,
      public readonly periodoGraciaLetras: string,
      public readonly numPagareEntidad: string,
      public readonly autorizaDebitoAutomatico: string,
      public readonly ciCEApartirDelMes: string,
      public readonly porcentajeCobertura: number,
      public readonly valorPesosDesembolso: number,
      public readonly ciValorCuotaExtra: number,
      public readonly numCredito: string,
      public readonly aval: string,
      public readonly creditoReembolsableEn: string,
      public readonly numeroPoliza: string,
      public readonly modalidadPagoCapital: string,
      public readonly tasaInteresMora: number,
      public readonly paisCreacion: string,
      public readonly periodicidadMuerto: string,
      public readonly listaApoderadoRepresentantePagare: any,
      public readonly periodoMuertoDe: string,
      public readonly otraModalidadPago: string,
      public readonly mensajeRespuesta: string,
      public readonly vis: string,
      public readonly baseLiquidacionPlazo: string,
      public readonly valorInteresesMora: number,
      public readonly porcentAmortizacionSemestral: number,
      public readonly valorComisionNumeros: number,
      public readonly numReferencia: string,
      public readonly periodoMuerto: string,
      public readonly periodoMuertoLetras: string,
      public readonly periodoGraciaDe: string,
      public readonly plazoLetras: string,
      public readonly apoderadoTipoId: string,
      public readonly periodicidadGracia: string,
      public readonly numUnidadesUVR: number,
      public readonly valorOtrosSegurosNumeros: number,
      public readonly numCuotas: number,
      public readonly fechaDesembolso: string,
      public readonly dtfEA: number,
      public readonly valorSeguroVidaLetras: string,
      public readonly valorCapitalNumero: number,
      public readonly listaAmortizaciones: any,
      public readonly construccionViviendaIndividual: string,
      public readonly plazoCreditoHasta: string,
      public readonly plazoNumero: number,
      public readonly otorganteNumId: string,
      public readonly garantiaAdicional: string,
      public readonly tasaInteresRenumEA: number,
      public readonly fechaGrabacionPagare: string,
      public readonly otroDestino: string,
      public readonly archivosAdjuntos: any,
      public readonly empresaOtorgante: string,
      public readonly ciudadDesembolso: string,
      public readonly codOficina: string,
      public readonly periodoGraciaNumero: number,
      public readonly otorganteTipoId: string,
      public readonly ciConPeriodoGracia: string,
      public readonly spreed: number,
      public readonly sucursal: string,
      public readonly valorInteresesLetras: string,
      public readonly modalidadPagosInteres: string,
      public readonly valorCuotaUVRLetras: string,
      public readonly baseLiquidacionTasa: string,
      public readonly valorOtrosSegurosLetras: string,
      public readonly periodoMuertoHasta: string,
      public readonly listaCodeudoresAvalistasPagare: any,
      public readonly textoAdicional: string,
      public readonly fechaVencimientoFinanciero: string,
      public readonly valorDesembolsoUVRLetras: string,
      public readonly seguroVida: string,
      public readonly idClaseDefinicionDocumento: string,
      public readonly periodoMuertoNumero: number,
      public readonly valorInteresesNumero: number,
      public readonly tasaNominal: number,
      public readonly fechaPagoPrimerCuotaMensual: string,
      public readonly valorCuotaUVR: number,
      public readonly idDocumentoPagare: string,
      public readonly tasaInteresMoraLetras: string,
      public readonly porcentAmortizacionMensual: number,
      public readonly nitEmisor: string,
      public readonly diaPago: number,
      public readonly valorPesosDiligenciaLetras: string,
      public readonly periodicidadPlazo: string,
      public readonly tipoPoliza: string,
      public readonly apoderadoCuenta: string,
      public readonly porcentajeComision: number,
      public readonly adquisicionVivienda: string,
      public readonly apoderadoNumId: string,
      public readonly valorPesosDesembolsoLetras: string,
      public readonly tasaInteresRenumEALetras: string,
      public readonly otorganteCuenta: string,
      public readonly regional: string,
      public readonly valorOtrosConceptosLetras: string,
      public readonly serialNumero: string,
      public readonly tasaInteresLetras: string,
      public readonly periodoGraciaHasta: string,
      public readonly valorOtrosConceptosNumeros: number,
      public readonly puntosPorcentualesRedescuento: number,
      public readonly cuenta: string,
      public readonly margenRedescuento: number,
      public readonly ciNumCuotasExtras: number,
      public readonly noVis: string,
      public readonly fechaPagoPrimerCuotaInteres: string,
      public readonly deptoCreacion: string,
      public readonly fechaPagoPrimerCuota: string,
      public readonly periodoGracia: string,
      public readonly valorPesosActual: number,
      public readonly ciudadCreacion: string,
      public readonly valorComisionLetras: string,
      public readonly mejoramientoViviendaInterSoci: string,
      public readonly plazoCreditoDe: string,
      public readonly tipoPagare: string,
      public readonly dtfDessembolso: number,
      public readonly ciCEPagaderaCada: string,
      public readonly fechaPagoPrimerCuotaCapital: string,
      public readonly valorPesosDiligenciamiento: number,
      public readonly fechaPagoPrimerCuotaSemestral: string,
      public readonly pais: string,
      public readonly tasaRedescuento: number,
      public readonly tasaNominalLetras: string,
      public readonly valorCapitalLetras: string,
      public readonly modalidad: string,
      public readonly numCuotasLetras: string,
      public readonly departamento: string,
      public readonly valorCuotaPesosLetras: string,
      public readonly destinoOperacion: string,
      public readonly tasaInteres: number,
      public readonly ciConCuotasExtras: string,
      public readonly valorSeguroVidaNumeros: number,
      public readonly valorCuotaPesos: number
    ) {}
  
    static create(object: { [key: string]: any }): DocumentoPagareServiceDTO {
      const {
        pagareId,
        amount,
        currency,
        dueDate,
        debtor,
        creditor,
        periodoGraciaLetras,
        numPagareEntidad,
        autorizaDebitoAutomatico,
        ciCEApartirDelMes,
        porcentajeCobertura,
        valorPesosDesembolso,
        ciValorCuotaExtra,
        numCredito,
        aval,
        creditoReembolsableEn,
        numeroPoliza,
        modalidadPagoCapital,
        tasaInteresMora,
        paisCreacion,
        periodicidadMuerto,
        listaApoderadoRepresentantePagare,
        periodoMuertoDe,
        otraModalidadPago,
        mensajeRespuesta,
        vis,
        baseLiquidacionPlazo,
        valorInteresesMora,
        porcentAmortizacionSemestral,
        valorComisionNumeros,
        numReferencia,
        periodoMuerto,
        periodoMuertoLetras,
        periodoGraciaDe,
        plazoLetras,
        apoderadoTipoId,
        periodicidadGracia,
        numUnidadesUVR,
        valorOtrosSegurosNumeros,
        numCuotas,
        fechaDesembolso,
        dtfEA,
        valorSeguroVidaLetras,
        valorCapitalNumero,
        listaAmortizaciones,
        construccionViviendaIndividual,
        plazoCreditoHasta,
        plazoNumero,
        otorganteNumId,
        garantiaAdicional,
        tasaInteresRenumEA,
        fechaGrabacionPagare,
        otroDestino,
        archivosAdjuntos,
        empresaOtorgante,
        ciudadDesembolso,
        codOficina,
        periodoGraciaNumero,
        otorganteTipoId,
        ciConPeriodoGracia,
        spreed,
        sucursal,
        valorInteresesLetras,
        modalidadPagosInteres,
        valorCuotaUVRLetras,
        baseLiquidacionTasa,
        valorOtrosSegurosLetras,
        periodoMuertoHasta,
        listaCodeudoresAvalistasPagare,
        textoAdicional,
        fechaVencimientoFinanciero,
        valorDesembolsoUVRLetras,
        seguroVida,
        idClaseDefinicionDocumento,
        periodoMuertoNumero,
        valorInteresesNumero,
        tasaNominal,
        fechaPagoPrimerCuotaMensual,
        valorCuotaUVR,
        idDocumentoPagare,
        tasaInteresMoraLetras,
        porcentAmortizacionMensual,
        nitEmisor,
        diaPago,
        valorPesosDiligenciaLetras,
        periodicidadPlazo,
        tipoPoliza,
        apoderadoCuenta,
        porcentajeComision,
        adquisicionVivienda,
        apoderadoNumId,
        valorPesosDesembolsoLetras,
        tasaInteresRenumEALetras,
        otorganteCuenta,
        regional,
        valorOtrosConceptosLetras,
        serialNumero,
        tasaInteresLetras,
        periodoGraciaHasta,
        valorOtrosConceptosNumeros,
        puntosPorcentualesRedescuento,
        cuenta,
        margenRedescuento,
        ciNumCuotasExtras,
        noVis,
        fechaPagoPrimerCuotaInteres,
        deptoCreacion,
        fechaPagoPrimerCuota,
        periodoGracia,
        valorPesosActual,
        ciudadCreacion,
        valorComisionLetras,
        mejoramientoViviendaInterSoci,
        plazoCreditoDe,
        tipoPagare,
        dtfDessembolso,
        ciCEPagaderaCada,
        fechaPagoPrimerCuotaCapital,
        valorPesosDiligenciamiento,
        fechaPagoPrimerCuotaSemestral,
        pais,
        tasaRedescuento,
        tasaNominalLetras,
        valorCapitalLetras,
        modalidad,
        numCuotasLetras,
        departamento,
        valorCuotaPesosLetras,
        destinoOperacion,
        tasaInteres,
        ciConCuotasExtras,
        valorSeguroVidaNumeros,
        valorCuotaPesos
      } = object;
  
      return new DocumentoPagareServiceDTO(
        pagareId,
        amount,
        currency,
        dueDate,
        debtor,
        creditor,
        periodoGraciaLetras,
        numPagareEntidad,
        autorizaDebitoAutomatico,
        ciCEApartirDelMes,
        porcentajeCobertura,
        valorPesosDesembolso,
        ciValorCuotaExtra,
        numCredito,
        aval,
        creditoReembolsableEn,
        numeroPoliza,
        modalidadPagoCapital,
        tasaInteresMora,
        paisCreacion,
        periodicidadMuerto,
        listaApoderadoRepresentantePagare,
        periodoMuertoDe,
        otraModalidadPago,
        mensajeRespuesta,
        vis,
        baseLiquidacionPlazo,
        valorInteresesMora,
        porcentAmortizacionSemestral,
        valorComisionNumeros,
        numReferencia,
        periodoMuerto,
        periodoMuertoLetras,
        periodoGraciaDe,
        plazoLetras,
        apoderadoTipoId,
        periodicidadGracia,
        numUnidadesUVR,
        valorOtrosSegurosNumeros,
        numCuotas,
        fechaDesembolso,
        dtfEA,
        valorSeguroVidaLetras,
        valorCapitalNumero,
        listaAmortizaciones,
        construccionViviendaIndividual,
        plazoCreditoHasta,
        plazoNumero,
        otorganteNumId,
        garantiaAdicional,
        tasaInteresRenumEA,
        fechaGrabacionPagare,
        otroDestino,
        archivosAdjuntos,
        empresaOtorgante,
        ciudadDesembolso,
        codOficina,
        periodoGraciaNumero,
        otorganteTipoId,
        ciConPeriodoGracia,
        spreed,
        sucursal,
        valorInteresesLetras,
        modalidadPagosInteres,
        valorCuotaUVRLetras,
        baseLiquidacionTasa,
        valorOtrosSegurosLetras,
        periodoMuertoHasta,
        listaCodeudoresAvalistasPagare,
        textoAdicional,
        fechaVencimientoFinanciero,
        valorDesembolsoUVRLetras,
        seguroVida,
        idClaseDefinicionDocumento,
        periodoMuertoNumero,
        valorInteresesNumero,
        tasaNominal,
        fechaPagoPrimerCuotaMensual,
        valorCuotaUVR,
        idDocumentoPagare,
        tasaInteresMoraLetras,
        porcentAmortizacionMensual,
        nitEmisor,
        diaPago,
        valorPesosDiligenciaLetras,
        periodicidadPlazo,
        tipoPoliza,
        apoderadoCuenta,
        porcentajeComision,
        adquisicionVivienda,
        apoderadoNumId,
        valorPesosDesembolsoLetras,
        tasaInteresRenumEALetras,
        otorganteCuenta,
        regional,
        valorOtrosConceptosLetras,
        serialNumero,
        tasaInteresLetras,
        periodoGraciaHasta,
        valorOtrosConceptosNumeros,
        puntosPorcentualesRedescuento,
        cuenta,
        margenRedescuento,
        ciNumCuotasExtras,
        noVis,
        fechaPagoPrimerCuotaInteres,
        deptoCreacion,
        fechaPagoPrimerCuota,
        periodoGracia,
        valorPesosActual,
        ciudadCreacion,
        valorComisionLetras,
        mejoramientoViviendaInterSoci,
        plazoCreditoDe,
        tipoPagare,
        dtfDessembolso,
        ciCEPagaderaCada,
        fechaPagoPrimerCuotaCapital,
        valorPesosDiligenciamiento,
        fechaPagoPrimerCuotaSemestral,
        pais,
        tasaRedescuento,
        tasaNominalLetras,
        valorCapitalLetras,
        modalidad,
        numCuotasLetras,
        departamento,
        valorCuotaPesosLetras,
        destinoOperacion,
        tasaInteres,
        ciConCuotasExtras,
        valorSeguroVidaNumeros,
        valorCuotaPesos
      );
    }
  }
  
  export class DebtorDTO {
    constructor(
      public readonly idType: string,
      public readonly idNumber: string,
      public readonly name: string,
      public readonly address: string,
      public readonly city: string,
      public readonly country: string
    ) {}
  
    static create(object: { [key: string]: any }): DebtorDTO {
      const {
        idType,
        idNumber,
        name,
        address,
        city,
        country
      } = object;
  
      return new DebtorDTO(
        idType,
        idNumber,
        name,
        address,
        city,
        country
      );
    }
  }
  
  export class CreditorDTO {
    constructor(
      public readonly idType: string,
      public readonly idNumber: string,
      public readonly name: string,
      public readonly address: string,
      public readonly city: string,
      public readonly country: string
    ) {}
  
    static create(object: { [key: string]: any }): CreditorDTO {
      const {
        idType,
        idNumber,
        name,
        address,
        city,
        country
      } = object;
  
      return new CreditorDTO(
        idType,
        idNumber,
        name,
        address,
        city,
        country
      );
    }
  }