export class CrearGiradorDTO {
  constructor(
    public readonly direccion2PersonaGrupo_PGP?: string,
    public readonly tiempoServicio?: string,
    public readonly fkIdDepartamentoDomicilio_Nat?: number,
    public readonly regitroSuper_Jur?: string,
    public readonly fax2PersonaGrupo_PGP?: string,
    public readonly telefono3PersonaGrupo_PGP?: string,
    public readonly fkIdCiudad_Jur?: number,
    public readonly numeroDocumento?: string,
    public readonly fechaCamara_Jur?: string,
    public readonly mensajeRespuesta?: string,
    public readonly numeroCelular?: string,
    public readonly fkIdPaisNacionalidad_Nat?: number,
    public readonly fkIdClasePersona?: number,
    public readonly fechaNacimiento_Nat?: string,
    public readonly fkIdPaisCamara_Jur?: number,
    public readonly agenteAutoretenedor_Jur?: string,
    public readonly fkIdDepartamentoExpedicion_Nat?: number,
    public readonly fkIdPais_Jur?: number,
    public readonly identificacionEmisor?: string,
    public readonly direccion1PersonaGrupo_PGP?: string,
    public readonly fechaConstitucion_Jur?: string,
    public readonly correoElectronico?: string,
    public readonly libroNo_Jur?: string,
    public readonly fechaExpedicion_Nat?: string,
    public readonly fkIdCiudadExpedicion_Nat?: number,
    public readonly fkIdCiudadDomicilio_Nat?: number,
    public readonly residente_Jur?: string,
    public readonly circuloNo_Jur?: string,
    public readonly camaraComercioNo_Jur?: string,
    public readonly segundoApellido_Nat?: string,
    public readonly fkIdTipoDocumento?: number,
    public readonly telefono2PersonaGrupo_PGP?: string,
    public readonly pensionado?: string,
    public readonly notariaNo_Jur?: string,
    public readonly direccion3PersonaGrupo_PGP?: string,
    public readonly fkIdDepartamento_Jur?: number,
    public readonly cuentaGirador?: number,
    public readonly fechaEscritura_Jur?: string,
    public readonly nombresNat_Nat?: string,
    public readonly declarante_Jur?: string,
    public readonly escrituraNo_Jur?: string,
    public readonly fax1PersonaGrupo_PGP?: string,
    public readonly fkIdPaisExpedicion_Nat?: number,
    public readonly razonSocial_Jur?: string,
    public readonly salario?: string,
    public readonly fax3PersonaGrupo_PGP?: string,
    public readonly estadoCivil?: string,
    public readonly listaRepresentantesLegales?: any[],
    public readonly fkIdPaisDomicilio_Nat?: number,
    public readonly fkIdCiudadCamara_Jur?: number,
    public readonly fkIdDepartamentoCamara_Jur?: number,
    public readonly telefono1PersonaGrupo_PGP?: string,
    public readonly primerApellido_Nat?: string
  ) {}

  static create(object: { [key: string]: any }): CrearGiradorDTO {
    return new CrearGiradorDTO(
      object.direccion2PersonaGrupo_PGP,
      object.tiempoServicio,
      object.fkIdDepartamentoDomicilio_Nat,
      object.regitroSuper_Jur,
      object.fax2PersonaGrupo_PGP,
      object.telefono3PersonaGrupo_PGP,
      object.fkIdCiudad_Jur,
      object.numeroDocumento,
      object.fechaCamara_Jur,
      object.mensajeRespuesta,
      object.numeroCelular,
      object.fkIdPaisNacionalidad_Nat,
      object.fkIdClasePersona,
      object.fechaNacimiento_Nat,
      object.fkIdPaisCamara_Jur,
      object.agenteAutoretenedor_Jur,
      object.fkIdDepartamentoExpedicion_Nat,
      object.fkIdPais_Jur,
      object.identificacionEmisor,
      object.direccion1PersonaGrupo_PGP,
      object.fechaConstitucion_Jur,
      object.correoElectronico,
      object.libroNo_Jur,
      object.fechaExpedicion_Nat,
      object.fkIdCiudadExpedicion_Nat,
      object.fkIdCiudadDomicilio_Nat,
      object.residente_Jur,
      object.circuloNo_Jur,
      object.camaraComercioNo_Jur,
      object.segundoApellido_Nat,
      object.fkIdTipoDocumento,
      object.telefono2PersonaGrupo_PGP,
      object.pensionado,
      object.notariaNo_Jur,
      object.direccion3PersonaGrupo_PGP,
      object.fkIdDepartamento_Jur,
      object.cuentaGirador,
      object.fechaEscritura_Jur,
      object.nombresNat_Nat,
      object.declarante_Jur,
      object.escrituraNo_Jur,
      object.fax1PersonaGrupo_PGP,
      object.fkIdPaisExpedicion_Nat,
      object.razonSocial_Jur,
      object.salario,
      object.fax3PersonaGrupo_PGP,
      object.estadoCivil,
      object.listaRepresentantesLegales,
      object.fkIdPaisDomicilio_Nat,
      object.fkIdCiudadCamara_Jur,
      object.fkIdDepartamentoCamara_Jur,
      object.telefono1PersonaGrupo_PGP,
      object.primerApellido_Nat
    );
  }
}